PTCG2win/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts_old/', include('accounts_old.urls')),  # アカウント管理
    path('accounts/', include('accounts.urls')),
    path('', include('decks.urls')),
]

accounts/urls.py
from django.urls import path, re_path, reverse_lazy

from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    # e.g. /decks/
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('reset/', auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url=reverse_lazy('accounts:password_reset_done'),
        ),
         name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
            name='password_reset_confirm'),
    path('reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path("settings/password/", auth_views.PasswordChangeView.as_view(template_name="accounts/password_change.html",
                                                                     success_url=
                                                                     reverse_lazy("accounts:password_change_done")),
         name="password_change"),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'),
        name='password_change_done')
]

decks/urls.py
from django.urls import path

from . import views


app_name = 'decks'
urlpatterns = [
    # e.g. /decks/
    path("", views.index, name="index"),
    # e.g. /decks/0/
    path("<int:deck_id>/", views.detail, name="detail"),
    # # e.g. /decks/search/?from=0&to=0
    # path("search/", views.search, name="search"),
    path("deck_board/", views.deck_board, name="deck_board"),

    path("card_post_search/", views.card_search_view, name="post_view"),
    path("card_search/", views.SearchSubmitView.as_view(), name="search-submit"),
    path("card_search_ajax/", views.SearchAjaxSubmitView.as_view(), name="search-ajax-submit"),

    path("new_deck_ajax/", views.NewDeckAjaxView.as_view(), name="deck_edit_ajax"),

    path("proxy_maker/", views.proxy_maker, name="proxy_maker"),
    path("proxy_maker_login/", views.proxy_maker_login, name="proxy_maker_login"),
    path("proxy_result/", views.proxy_result, name="proxy_result"),

    path("cards/<int:card_id>/", views.card_view, name="card_view")
]

decks/models.py
from django.db import models
from accounts.models import PTCG2winUser


class Region(models.Model):
    name = models.CharField(max_length=30)
    name_j = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Expansion(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    pub_date = models.DateField(null=True)
    code = models.CharField(max_length=10)
    logo_url = models.CharField(max_length=2000, null=True)
    symbol_url = models.CharField(max_length=2000, null=True)
    info_url = models.CharField(max_length=2000)
    total_cards = models.IntegerField(null=True)
    series = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name


class Regulation(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=False)
    expansions = models.ManyToManyField(Expansion)

    def __str__(self):
        return self.name


class Rarity(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class PokemonRegion(models.Model):
    name = models.CharField(max_length=30)
    name_j = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class PokemonSpecies(models.Model):
    name = models.CharField(max_length=20)
    name_j = models.CharField(max_length=10)
#    form_name = models.CharField(max_length=20, default="")
    pokedex_number = models.IntegerField()
    region = models.ForeignKey(PokemonRegion, on_delete=models.PROTECT)
    evolves_from = models.ForeignKey('self', on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name


class SuperType(models.Model):
    name = models.CharField(max_length=20)
    name_j = models.CharField(max_length=20, default="みてい")

    def __str__(self):
        return self.name


class SubType(models.Model):
    name = models.CharField(max_length=20)
    name_j = models.CharField(max_length=20, default="みてい")
    supertype = models.ForeignKey(SuperType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class CardName(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class CardText(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Card(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.PROTECT)
    set = models.ForeignKey(Expansion, on_delete=models.PROTECT)
    global_id_number = models.CharField(max_length=30)
    name = models.ForeignKey(CardName, on_delete=models.PROTECT)
    id_in_expansion = models.CharField(max_length=30, null=True)
    rarity = models.ForeignKey(Rarity, on_delete=models.PROTECT, null=True, default=None)
    is_prism_star = models.BooleanField(default=False)
    supertype = models.ForeignKey(SuperType, on_delete=models.PROTECT)
    subtype = models.ForeignKey(SubType, on_delete=models.PROTECT)
    text = models.ManyToManyField(CardText)
    image_url = models.CharField(max_length=200, null=True, default="")

    def __str__(self):
        return self.name.name


class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Weakness(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    value = models.CharField(max_length=10)
    # e.g. "*2" "+30"

    def __str__(self):
        return self.name


class Resistance(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    value = models.CharField(max_length=10)
    # e.g. "*2" "+30"

    def __str__(self):
        return self.name


class Pokemon(Card):
    hp = models.IntegerField()
    retreat_cost = models.IntegerField()
    weakness = models.ForeignKey(Weakness, on_delete=models.PROTECT, null=True)
    resistance = models.ForeignKey(Resistance, on_delete=models.PROTECT, null=True)
    # species = models.ForeignKey(PokemonSpecies, on_delete=models.PROTECT)
    evolves_from = models.CharField(max_length=40, null=True, default=None)
    evolution_list_str = models.CharField(max_length=200)
    types = models.ManyToManyField(Type)


#
# class BasicPokemon(Pokemon):
#     pass
#
#
# class StageOnePokemon(Pokemon):
#     evolves_from = models.CharField(max_length=20)
#
#
# class StageTwoPokemon(Pokemon):
#     evolves_from = models.CharField(max_length=20)
#
#
# class BreakPokemon(Pokemon):
#     evolves_from = models.CharField(max_length=20)
#
#
# class EXPokemon(Pokemon):
#     text = models.CharField(max_length=50)
#
#
# class MegaEXPokemon(EXPokemon):
#     evolves_from = models.CharField(max_length=20)
#
#
# class GXBasicPokemon(BasicPokemon):
#     text = models.CharField(max_length=50)
#
#
# class GXStageOnePokemon(StageOnePokemon):
#     text = models.CharField(max_length=50)
#
#
# class GXStageTwoPokemon(StageTwoPokemon):
#     text = models.CharField(max_length=50)




# class Stadium(Trainers):
#     pass
#
#
# class Item(Trainers):
#     pass
#
#
# class Supporter(Trainers):
#     pass


class AbilityType(models.Model):
    name = models.CharField(max_length=50)
    name_j = models.CharField(max_length=50, default="みてい")

    def __str__(self):
        return self.name


class Ability(models.Model):
    name = models.CharField(max_length=50)
    text = models.CharField(max_length=500)
    type = models.ForeignKey(AbilityType, on_delete=models.PROTECT)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class AttackCost(models.Model):
    # nameは、','.join(cost_list)とすること。
    name = models.CharField(max_length=300)
    convertedEnergyCost = models.IntegerField(default=0)

    grass = models.IntegerField(default=0)
    fire = models.IntegerField(default=0)
    water = models.IntegerField(default=0)
    lightning = models.IntegerField(default=0)
    fighting = models.IntegerField(default=0)
    colorless = models.IntegerField(default=0)
    darkness = models.IntegerField(default=0)
    metal = models.IntegerField(default=0)
    fairly = models.IntegerField(default=0)
    free = models.IntegerField(default=0)

    dragon = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_list(self):
        return self.name.split(",")


class Attack(models.Model):
    name = models.CharField(max_length=30)
    damage = models.CharField(max_length=20)
    text = models.CharField(max_length=200)
    cost = models.ForeignKey(AttackCost, on_delete=models.PROTECT)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ArchType(models.Model):
    name = models.CharField(max_length=100)
    regulation = models.ForeignKey(Regulation, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Deck(models.Model):
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    mod_date = models.DateTimeField()
    description = models.CharField(max_length=21500)
    owner = models.ForeignKey(PTCG2winUser, on_delete=models.PROTECT)
    regulation = models.ForeignKey(Regulation, on_delete=models.PROTECT)
    arch_type = models.ForeignKey(ArchType, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class DeckList(models.Model):
    parent_deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    deck_code = models.CharField(max_length=20, null=True)
    created_date = models.DateTimeField()

    def __str__(self):
        return self.deck_code


class CardBundle(models.Model):
    card = models.ForeignKey(Card, on_delete=models.PROTECT)
    amount = models.IntegerField(default=1)
    parent_deck_list = models.ForeignKey(DeckList, on_delete=models.CASCADE)

    def __str__(self):
        return self.card.name.name


class Topic(models.Model):
    name = models.CharField(max_length=150, default="Title is not set.")
    date = models.DateTimeField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    date = models.DateTimeField()
    user = models.ForeignKey(PTCG2winUser, on_delete=models.PROTECT)
    text = models.CharField(max_length=10000, default="Comment text is not set.")

    def __str__(self):
        return self.text


class DeckTopic(Topic):
    parent_deck = models.ForeignKey(Deck, on_delete=models.CASCADE)


class DeckCode(models.Model):
    date = models.DateTimeField()
    text = models.CharField(max_length=24, default="Invalid deck code.")
    ip = models.CharField(max_length=39, default="0.0.0.0")

    def __str__(self):
        return self.text

decks/forms.py
from django import forms
from .models import *


class DeckRegisterForm(forms.ModelForm):

    class Meta:
        model = Deck
        fields = ("name", "description", "regulation", "arch_type", )
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "example: Reshiram GX Deck"}),
            "description": forms.Textarea(attrs={"rows": 5}),
            # "regulation": forms.ChoiceField(choices=[obj.name for obj in Regulation.objects.all()]),
            # "arch_type": forms.ChoiceField(choices=[arch_obj.name for arch_obj in ArchType.objects.all()]),
        }

decks/templates/decks/_base.html
{% load static %}<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock title %} | PTCG2win</title>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120934676-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-120934676-1');
    </script>
    {% block stylesheet %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body style="padding-top:4.5rem;" class="m-3">
{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href={% url 'decks:index' %}>PTCG2win</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
                aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href={% url 'decks:index' %}>トップ </a>#}
{#                </li>#}
                <li class="nav-item active">
                    <a class="nav-link" href={% url 'decks:proxy_maker' %}>プロキシ印刷</a>
                </li>
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{% url "decks:post_view" %}">カード検索</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">デッキ投稿・検索(未実装)</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">オンライン対戦(未実装)</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{##}
{#                    <form class="form-inline my-2 my-lg-0">#}
{#                        <input class="form-control" type="text" placeholder="サイト内検索(未実装)">#}
{#                    </form>#}
{#                </li>#}
            </ul>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href="#">My account</a>
                                <a class="dropdown-item" href="#">Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>


    <div class="container">
        {% if disable_breadcrumb %}

        {% else %}

            <ol class="breadcrumb">
                {% block breadcrumb %}
                {% endblock %}
            </ol>
        {% endif %}
        {# Start content #}
        {% block content %}
        {% endblock %}
        {# End content #}
    </div>
{% endblock %}
{# jQuery first, then Tether, then Bootstrap JS. #}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous" defer></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intercooler-js/1.2.1/intercooler.min.js" defer></script>
</body>
</html>

decks/templates/decks/card_view.html
{% extends "decks/_base.html" %}

{% block title %}{{ card.name.name }}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">Cards</li>
  <li class="breadcrumb-item active">{{ card }}</li>
{% endblock %}
{% block content %}

    <div>{{ card.name }} - {{ card.id_in_expansion }}</div>
    <img src="{{ card.image_url }}">
    <br clear="">
    <code class="prettyprint linenums">{{ card.fields }}</code>




{% endblock %}

decks/templates/decks/deck_board.html
{% extends "decks/_base.html" %}
{% load static %}

{% block title %}Deck Board{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">Decks</li>
  <li class="breadcrumb-item active">Board</li>
{% endblock %}
{% block content %}
    <div class="container">
        <ul class="list-group">
            {% for deck in decks_to_show %}
                <li style='border-style: solid;list-style: none;'>
                    <a href="{% url 'decks:detail' deck.id %}">
                        <div class="deck-tile row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                <span class="deck-name" style="background-image:url('{% static "img/ninetales.png" %}')">
                                {{ deck.name }}</span>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3">
                                <span>メインポケモンの画像をここに表示</span>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3">
                                <span class="deck-name" style="background-image:url('{% static "img/ninetales.png" %}')">
                                <span class="text-dark"> 作者: </span>{{ deck.owner.nick_name }}</span>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-0">
                                その他の情報をなんか表示
                            </div>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

decks/templates/decks/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ deck.name }} - Detail</title>
</head>
<body>
<h1>{{ deck.name }}</h1>

<ul>
    {% for cardbundle in deck.cardbundle_set.all %}
        <li>
            {{ cardbundle.card.name }} : {{ cardbundle.amount }}
        </li>
    {% endfor %}

</ul>
</body>
</html>

decks/templates/decks/index.html
{% extends "decks/_base.html" %}

{% block title %}トップページ{% endblock %}

{% block content %}
    <div class="card card-block p-3 mb-3">
        <h4 class="card-title">About</h4>
        <p class="card-text">
            このサイトは、ポケモンカードゲームのコミュニティサイトになる予定です。<br/>
            ポケモンカードゲームをより手軽に、オープンに、そして活発に競技として楽しめるようにすることを目標として制作しています。<br/>
            デッキ共有や議論、サイト上での模擬対戦、対戦結果の統計データの公開等ができるプラットフォームを作っていく予定です。
        </p>
        <p class="card-text">
            This site is going to be a community site of Pokemon TCG.<br/>
            The final goal is to make the competitive Pokemon TCG play more open, active and easier to enjoy. <br/>
            We're going to set up deck builder, online play simulator, statistics based on the data from the
            simulator here.
        </p>
    </div>
    <div>
        <p>
            Todo:<br/>
            ・デッキの登録フォームを作る<br/>
            ・Unityの使い方を学ぶ<br/>
            ・Unityで試合ができる対戦シミュレータを作る<br/>
            ・カードの個別ビューのページをまともにする<br/>
        </p>

    </div>
    {% comment %}

    {% if latest_deck_list %}
        <ul>
            {% for deck in latest_deck_list %}
                <li><a href="{% url 'decks:detail' deck.id %}">{{ deck.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No decks are available.</p>
    {% endif %}

    {% endcomment %}
{% endblock %}

decks/templates/decks/new_deck.html
{% extends "decks/_base.html" %}
{% load static %}

{% block title %}デッキを登録{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">Decks</li>
    <li class="breadcrumb-item active">Board</li>
{% endblock %}


{% block content %}
    <div class="container">
        <form id="form" role="form" action="{% url 'decks:search-submit' %}" method="post">
            {% csrf_token %}
            <input name="search"
                   id="search"
                   type="search"
                   placeholder="Start typing here"
                   ic-post-to="{% url 'decks:search-ajax-submit' %}"
                   ic-trigger-on="keyup changed"
                   ic-trigger-delay="300ms"
                   ic-target="#search-result-container"/>
            <button type="submit">Search</button>
        </form>
        <span id="search-result-container"></span>

        <div id="deck-table-container"></div>
    </div>

{% endblock %}

decks/templates/decks/new_deck_ajax.html
<!-- This is the search_results.html sub-template -->
{% if deck %}
	<h3>Your deck is: <i>{{ deck.name }}</i></h3>
	{% if related_card_bundles %}
		<ul>
		{% for card_bundle in related_card_bundles %}
            <li><a href="{% url 'decks:card_view' card_id=card_bundle.card.global_id_number %}">{{ card_bundle.card.name }} </a>, {{ card_bundle.amount }}</li>
		{% endfor %}
		</ul>
	{% endif %}
{% endif %}

decks/templates/decks/proxy_maker.html
{% extends "decks/_base.html" %}

{% block title %}デッキコード -> 印刷用PDF{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Proxy Maker</li>
{% endblock %}

{% block content %}
    <h4>- 使い方</h4>
    <p>
        <a href="https://www.pokemon-card.com/deck/index.html" target="_blank">デッキ構築 | ポケモンカードゲーム公式ホームページ</a><br/>
        ↑の「デッキ作成ツール」でカードを選んで、作成したデッキコードから印刷用のPDFをダウンロードできます。<br/>
    <p>
        A4の紙に等倍で印刷してください。<br/>
        セブンイレブン等のネットプリントサービスと組み合わせることで、外出先での印刷も可能です。
    </p>

    <div class="card mt-3 mb-3">
        <div class="card-block">
            <div class="card-header">デッキコード -> 印刷用PDF</div>
            <form action="/proxy_result" method="get">

                {% for field in form %}
                    {# Todo: ハードコード部分要修正。 #}
                    {% if field.label == "ファイルタイプ" %}

                        <div class="btn-group m-2 mx-3" data-toggle="buttons">
                            <label class="btn btn-outline-primary active">
                                <input name="type" value="pdf" id="pdf" checked="" type="radio">PDF（印刷用）
                            </label>
                            <label class="btn btn-outline-info">
                                <input name="type" value="csv" id="csv" type="radio">CSV（デッキリスト用）
                            </label>
                        </div>

                    {% else %}

                        <div class="input-group mt-4 mx-3 mb-0">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="{{ field.name }}">{{ field.label }}</label>
                            </div>
                            {{ field }}

                        </div>
                    {% endif %}
                {% endfor %}
                <br>
                <div class="btn-group mx-3 mb-4">
                    <button type='submit' class="btn btn-primary">ダウンロード</button>
                </div>
            </form>
        </div>
    </div>
    <div class="mx-3">
        <h4 class="mt-3 mb-2">更新履歴</h4>
        <ul class="list-group">
            2022-06-09
            <li class="list-group-item">
                一部の基本エネルギーの画像がうまく読み込まれなかった問題を修正<br />
                けんと修正ありがとう！！
            </li>
            2021-09-20
            <li class="list-group-item">
                V-UNIONの印刷に対応
            </li>
            <li class="list-group-item">
                出力ファイルのファイルサイズを縮小
            </li>
            <li class="list-group-item">
                その他エラーになっていたケースを修正
            </li>
        </ul>
    </div>

{% endblock %}

decks/templates/decks/search_results.html
<!-- This is the search_results.html sub-template -->
{% if query %}
	<h3>You searched for: <i>{{ query }}</i></h3>
	<p>{{ title }}</p>
	{% if items %}
		<ul>
		{% for item in items %}
			<li>{{ item|safe }}</li>
		{% endfor %}
		</ul>
	{% endif %}
{% endif %}

decks/templates/decks/search_submit.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Search Results</title>
	</head>
	<body>
		{% if query %}
			{% include 'decks/search_results.html' %}
		{% else %}
			<h1 class="h3">Nothing found. <br>Try entering valid search term.</h1>
		{% endif %}
	</body>
</html>